title: "Cookie 解体新書"
summary: |+
  Web 技術解体新書
  第二章 Cookie 解体新書
topics: ["cookie", "tech", "web"]
published: false
price: 1000
chapters:
  - 0_intro.md
  - 1_session.md
  - 2_credential.md
  - 3_secure.md
  - 4_3rd-party.md
